In [10]:
import numpy as n
from numpy import linalg as LA
w, v = LA.eig(np.diag((1, 2, 3)))
w; v

[[1 2 3]
 [1 1 1]
 [3 3 3]]


In [3]:
print(w)

[1. 2. 3.]


In [4]:
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
